image: java:8

stages:
  - build jar

build:
  image: maven:3.6.3-jdk-11-slim
  stage: build jar
  script:
    - mvn clean install && mvn package -B
  artifacts:
    paths:
      - target/*.jar




    
