image: gitlab/dind
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: 40233306
  APP_NAME: GlenJavaRestApi
  REPO: GlenJavaRestApi

stages:
  - build

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "./rest-service/mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar




    
